Asn_23/Controllers/MVCReportController.cs
using Asn_23.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asn_23.Controllers
{
    [Authorize(Roles = "Administrator,Reporter,Worker")]
    public class MVCReportController : Controller
    {
        // GET: MVCReport
        public ActionResult Index()
        {
            GoodSamaritanContext ctx = new GoodSamaritanContext();

            IEnumerable<SelectListItem> siYears = (from c in ctx.FiscalYears
                                                   select new { c.FiscalYearId, c.Years }).AsEnumerable()
                                                   .Select(m => new SelectListItem()
                                                   {
                                                       Value = m.FiscalYearId.ToString(),
                                                       Text = m.Years
                                                   });

            List<dynamic> siMonths = new List<dynamic>();
            siMonths.Add(new SelectListItem() { Value = "1", Text = "January" });
            siMonths.Add(new SelectListItem() { Value = "2", Text = "February" });
            siMonths.Add(new SelectListItem() { Value = "3", Text = "March" });
            siMonths.Add(new SelectListItem() { Value = "4", Text = "April" });
            siMonths.Add(new SelectListItem() { Value = "5", Text = "May" });
            siMonths.Add(new SelectListItem() { Value = "6", Text = "June" });
            siMonths.Add(new SelectListItem() { Value = "7", Text = "July" });
            siMonths.Add(new SelectListItem() { Value = "8", Text = "August" });
            siMonths.Add(new SelectListItem() { Value = "9", Text = "September" });
            siMonths.Add(new SelectListItem() { Value = "10", Text = "October" });
            siMonths.Add(new SelectListItem() { Value = "11", Text = "November" });
            siMonths.Add(new SelectListItem() { Value = "12", Text = "December" });
            ViewBag.yearsSelect = new SelectList(siYears, "Value", "Text");
            ViewBag.monthsSelect = new SelectList(siMonths, "Value", "Text");

            if(TempData["Error"] != null)
            {
                ViewBag.Message = TempData["Error"];
            }
            return View();
        }

        // POST: MVCReport/DisplayReport
        [HttpPost]
        public ActionResult Report()
        {
            if(Request.Form["selectMonth"].Length < 1 || Request.Form["selectYear"].Length < 1 )
            {
                TempData["Error"] = "Please select a month and a year";
                return RedirectToAction("Index");
            }

            int monthnum = int.Parse(Request.Form["selectMonth"]);
            int yearid = int.Parse(Request.Form["selectYear"]);

            GoodSamaritanContext ctx = new GoodSamaritanContext();
            
            ViewBag.genderMale = (from c in ctx.Clients
                                  where c.Month == monthnum
                                  where c.FiscalYearId == yearid
                                  where c.Gender == "Male"
                                  select c).Count();

            ViewBag.genderFemale = (from c in ctx.Clients
                                    where c.Month == monthnum
                                    where c.FiscalYearId == yearid
                                    where c.Gender == "Female"
                                    select c).Count();

            ViewBag.genderTrans = (from c in ctx.Clients
                                   where c.Month == monthnum
                                   where c.FiscalYearId == yearid
                                   where c.Gender == "Trans"
                                   select c).Count();
            ViewBag.age12_19 = (from c in ctx.Clients
                                where c.Month == monthnum
                                where c.FiscalYearId == yearid
                                where c.Age.Range == "Youth >12<19"
                                select c).Count();

            ViewBag.age13 = (from c in ctx.Clients
                             where c.Month == monthnum
                             where c.FiscalYearId == yearid
                             where c.Age.Range == "Child <13"
                             select c).Count();

            ViewBag.age18_25 = (from c in ctx.Clients
                                where c.Month == monthnum
                                where c.FiscalYearId == yearid
                                where c.Age.Range == "Youth >18<25"
                                select c).Count();

            ViewBag.age24_65 = (int)(from c in ctx.Clients
                                     where c.Month == monthnum
                                     where c.FiscalYearId == yearid
                                     where c.Age.Range == "Adult >24<65"
                                     select c).Count();

            ViewBag.age64 = (from c in ctx.Clients
                             where c.Month == monthnum
                             where c.FiscalYearId == yearid
                             where c.Age.Range == "Senior >64"
                             select c).Count();

            ViewBag.statusReopened = (from c in ctx.Clients
                                      where c.Month == monthnum
                                      where c.FiscalYearId == yearid
                                      where c.StatusOfFile.Status == "Reopened"
                                      select c).Count();

            ViewBag.statusOpen = (from c in ctx.Clients
                                     where c.Month == monthnum
                                     where c.FiscalYearId == yearid
                                     where c.StatusOfFile.Status == "Open"
                                     select c).Count();

            ViewBag.statusClosed = (from c in ctx.Clients
                                       where c.Month == monthnum
                                       where c.FiscalYearId == yearid
                                       where c.StatusOfFile.Status == "Closed"
                                       select c).Count();
            
            ViewBag.programCrisis = (from c in ctx.Clients
                                        where c.Month == monthnum
                                        where c.FiscalYearId == yearid
                                        where c.Program.Type == "Crisis"
                                        select c).Count();

            ViewBag.programCourt = (from c in ctx.Clients
                                       where c.Month == monthnum
                                       where c.FiscalYearId == yearid
                                       where c.Program.Type == "Court"
                                       select c).Count();

            ViewBag.programSMART = (from c in ctx.Clients
                                       where c.Month == monthnum
                                       where c.FiscalYearId == yearid
                                       where c.Program.Type == "SMART"
                                       select c).Count();

            ViewBag.programDVU = (from c in ctx.Clients
                                     where c.Month == monthnum
                                     where c.FiscalYearId == yearid
                                     where c.Program.Type == "DVU"
                                     select c).Count();

            ViewBag.programMCFD = (from c in ctx.Clients
                                      where c.Month == monthnum
                                      where c.FiscalYearId == yearid
                                      where c.Program.Type == "MCFD"
                                      select c).Count();

            

            ViewBag.currentdate = DateTime.Now.ToString("MMMM dd/yyyy");

            ViewBag.year = (from c in ctx.FiscalYears
                            where c.FiscalYearId == yearid
                            select c.Years).First().ToString();

            String[] monthArray = {"January", "February", "March", "April", "May", "June", "July", "August",
                                  "September", "October", "November", "December"};

            ViewBag.month = monthArray[monthnum-1];
            return View();
        }
    }
}

Asn_23/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Asn_23.Models;
using Newtonsoft.Json;

namespace Asn_23.Controllers
{
    [Authorize(Roles = "Administrator,Reporter,Worker")]
    public class ReportController : ApiController
    {
        public class YearObj
        {
            public int id;
            public string year;
        }

        public class ReportObj
        {
            public int genderFemale;
            public int genderMale;
            public int genderTrans;

            public int age24_65;
            public int age18_25;
            public int age12_19;
            public int age13;
            public int age64;

            public int statusOpen;
            public int statusClosed;
            public int statusReopened;

            public int programCrisis;
            public int programCourt;
            public int programSMART;
            public int programDVU;
            public int programMCFD;
        }


        // GET api/report/getyear
        public IEnumerable<YearObj> GetYear()
        {
            GoodSamaritanContext ctx = new GoodSamaritanContext();
            List<YearObj> yearList = new List<YearObj>();
            var qry = (from c in ctx.FiscalYears
                      select new { c.FiscalYearId, c.Years });
            foreach (var item in qry)
            {
                yearList.Add(new YearObj { id = item.FiscalYearId, year = item.Years });
            }

            return yearList;
        }

        [HttpGet]
        public ReportObj GetReport(int monthnum, int yearid)
        {
            GoodSamaritanContext ctx = new GoodSamaritanContext();
            ReportObj reportData = new ReportObj();

            reportData.genderMale = (from c in ctx.Clients
                                     where c.Month == monthnum
                                     where c.FiscalYearId == yearid
                                     where c.Gender == "Male"
                                     select c).Count();
            reportData.genderFemale = (from c in ctx.Clients
                                       where c.Month == monthnum
                                       where c.FiscalYearId == yearid
                                       where c.Gender == "Female"
                                       select c).Count();
            reportData.genderTrans = (from c in ctx.Clients
                                      where c.Month == monthnum
                                      where c.FiscalYearId == yearid
                                      where c.Gender == "Trans"
                                      select c).Count();

            reportData.age24_65 = (int)(from c in ctx.Clients
                                        where c.Month == monthnum
                                        where c.FiscalYearId == yearid
                                        where c.Age.Range == "Adult >24<65"
                                        select c).Count();

            reportData.age18_25 = (from c in ctx.Clients
                                   where c.Month == monthnum
                                   where c.FiscalYearId == yearid
                                   where c.Age.Range == "Youth >18<25"
                                   select c).Count();

            reportData.age12_19 = (from c in ctx.Clients
                                   where c.Month == monthnum
                                   where c.FiscalYearId == yearid
                                   where c.Age.Range == "Youth >12<19"
                                   select c).Count();

            reportData.age13 = (from c in ctx.Clients
                                where c.Month == monthnum
                                where c.FiscalYearId == yearid
                                where c.Age.Range == "Child <13"
                                select c).Count();

            reportData.age64 = (from c in ctx.Clients
                                where c.Month == monthnum
                                where c.FiscalYearId == yearid
                                where c.Age.Range == "Senior >64"
                                select c).Count();

            reportData.statusOpen = (from c in ctx.Clients
                                    where c.Month == monthnum
                                    where c.FiscalYearId == yearid
                                    where c.StatusOfFile.Status == "Open"
                                    select c).Count();
            reportData.statusClosed = (from c in ctx.Clients
                                     where c.Month == monthnum
                                     where c.FiscalYearId == yearid
                                     where c.StatusOfFile.Status == "Closed"
                                     select c).Count();
            reportData.statusReopened = (from c in ctx.Clients
                                     where c.Month == monthnum
                                     where c.FiscalYearId == yearid
                                     where c.StatusOfFile.Status == "Reopened" 
                                     select c).Count();

            reportData.programCrisis = (from c in ctx.Clients
                                         where c.Month == monthnum
                                         where c.FiscalYearId == yearid
                                         where c.Program.Type == "Crisis"
                                         select c).Count();
            reportData.programCourt = (from c in ctx.Clients
                                        where c.Month == monthnum
                                        where c.FiscalYearId == yearid
                                        where c.Program.Type == "Court"
                                           select c).Count();

            reportData.programSMART = (from c in ctx.Clients
                                        where c.Month == monthnum
                                        where c.FiscalYearId == yearid
                                        where c.Program.Type == "SMART"
                                           select c).Count();

            reportData.programDVU = (from c in ctx.Clients
                                        where c.Month == monthnum
                                        where c.FiscalYearId == yearid
                                        where c.Program.Type == "DVU"
                                         select c).Count();

            reportData.programMCFD = (from c in ctx.Clients
                                        where c.Month == monthnum
                                        where c.FiscalYearId == yearid
                                        where c.Program.Type == "MCFD"
                                          select c).Count();

            return reportData;
        }
    }
}

Asn_23/Views/MVCReport/Index.cshtml
@{
    ViewBag.Title = "Select Report Period";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SelectList years = ViewBag.yearsSelect;
    SelectList months = ViewBag.monthsSelect;
}
<div class="container">
    <div class="row">
        <div class="form-horizontal center-block text-center">
            <h3>Select month and year</h3>
            <div>
                @using (Html.BeginForm("Report", "MVCReport", FormMethod.Post))
                {
                    @Html.DropDownList("selectMonth", months, "Month");
                    @Html.DropDownList("selectYear", years, "Year")
                    <input type="submit" value="Go" />
                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class="text-center col-sm-2 col-sm-push-5">
            <div class="center-block alert-danger">
                @ViewBag.Message
            </div>
        </div>
    </div>
    
</div>

Asn_23/Views/MVCReport/Report.cshtml
@{
    ViewBag.Title = "Month End Statistics";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="margin-top:20px;min-width:750px;">
    <div class="text-center">
        @Html.ActionLink("<< Back", "Index")
    </div>
    <div class="jumbotron">
        <div><p class="text-center">MONTH END STATISTICS</p></div>
        <p>Report Date: @ViewBag.currentdate</p>
        <!--BEGIN REPORT FOR MONTH/YEAR SECTION-->
        <div class="row">
            <div class="col-sm-8">
                <div class="col-sm-4">
                    REPORT FOR
                </div>
                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-6">
                            MONTH
                        </div>
                        <div class="col-sm-6">
                            @ViewBag.month
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            YEAR
                        </div>
                        <div class="col-sm-6">
                            @ViewBag.year
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--END REPORT FOR MONTH/YEAR SECTION-->
    </div>

    <!--Status Section-->
    <div class="row">
        <div class="col-sm-4">
            <h3>Status</h3>
        </div>
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-12">
                    Open
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    Closed
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    Reopened
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.statusopen
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.statusclosed
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.statusreopened
                </div>
            </div>
        </div>
    </div>
    <!--END STATUS SECTION-->
    <hr />
    <!--Program Section-->
    <div class="row">
        <!--Program column-->
        <div class="col-sm-4">
            <h3>Program</h3>
        </div>
        <!--Attributes column-->
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-12">
                    Crisis
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    Court
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    SMART
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    DVU
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    MCFD
                </div>
            </div>
        </div>
        <!--Values column-->
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.programcrisis
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.programcourt
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.programsmart
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.programdvu
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.programmcfd
                </div>
            </div>
        </div>
    </div>
    <!--END STATUS SECTION-->
    <hr />
    <!--GENDERS SECTION-->
    <div class="row">
        <!--Gender column-->
        <div class="col-sm-4">
            <h3>Gender</h3>
        </div>
        <!--Attributes column-->
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-12">
                    Female
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    Male
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    Trans
                </div>
            </div>
        </div>
        <!--Values column-->
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.genderfemale
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.gendermale                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.gendertrans
                </div>
            </div>
        </div>
    </div>
    <!--END GENDER SECTION-->
    <hr />
    <!--AGE SECTION-->
    <div class="row">
        <!--Gender column-->
        <div class="col-sm-4">
            <h3>Age</h3>
        </div>
        <!--Attributes column-->
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-12">
                    Adult >24 < 65
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    Youth >18 < 25
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    Youth >12 < 19
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    Child < 13
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    Senior > 64
                </div>
            </div>
        </div>
        <!--Values column-->
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.age24_65
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.age18_25
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.age12_19
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.age13
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 text-right">
                    @ViewBag.age64
                </div>
            </div>
        </div>
    </div>
    <!--END AGE SECTION-->
</div>